### ISSUE TITLE
OH3

### ISSUE THREAD

**Issue by rdsivd** [themillhousegroup/openhab2-addons#13]
## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
Hi,
i have made a widget in oh3 for remote ir :
[https://community.openhab.org/t/oh3-ui-ir-widget/108293/3](https://community.openhab.org/t/oh3-ui-ir-widget/108293/3)

i added the jar file in the oh3 addons lib, and it is not availble in oh3.
I think this is normal ?
when will there a version for oh3 ?

regards,
Ronny

**Comment by themillhousegroup** [comment]
It's very much the goal to get this binding compatible with OH3 and get it merged into the main codebase. 
I can't give a timeline unfortunately but it's definitely coming!

**Comment by rdsivd** [comment]
Thanks

Regards,
Ronny

Van: themillhousegroup <notifications@github.com>
Verzonden: woensdag 2 december 2020 3:45
Aan: themillhousegroup/openhab2-addons <openhab2-addons@noreply.github.com>
CC: Ronny Desmedt <r.desmedt@live.be>; Author <author@noreply.github.com>
Onderwerp: Re: [themillhousegroup/openhab2-addons] OH3 (#13)


It's very much the goal to get this binding compatible with OH3 and get it merged into the main codebase.
I can't give a timeline unfortunately but it's definitely coming!

**Comment by themillhousegroup** [comment]
Beta releases for 3.1 now available @rdsivd !

**Comment by rdsivd** [comment]
Thanks

I will test it and let you know the result

Regards
Ronny

Van: themillhousegroup <notifications@github.com>
Verzonden: woensdag 20 januari 2021 5:49
Aan: themillhousegroup/openhab2-addons <openhab2-addons@noreply.github.com>
CC: Ronny Desmedt <r.desmedt@live.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [themillhousegroup/openhab2-addons] OH3 (#13)


Beta releases for 3.1 now available @rdsivd<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frdsivd&data=04%7C01%7C%7C89d6b2e94fe44a68d8f808d8bcfeb604%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637467149440392912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t5reGWMavQaf1iJtrPL%2BKZDWxcuOJUqIQExKdRQlyks%3D&reserved=0> !

-
